[tool.black]
line-length = 79
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["main"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
plugins = ["sqlmypy"]

[[tool.mypy.overrides]]
module = "test-gitlab-ci-python-advanced.main.models"
