name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run isort
        run: isort --check --diff main

      - name: Run black
        run: black --check --diff main

      - name: Run flake8
        run: flake8 main

      - name: Run mypy
        run: mypy main --strict --ignore-missing-imports

      - name: Run tests
        run: pytest -v tests
